language: node_js
node_js:
  - '8'
  - '10'
script:
  - cd integration_tests/benchmarks && yarn && yarn test-travis && cd ../../
  - yarn && yarn build && yarn lint && if [[ $(node -v) = *v10* ]]; then yarn test-all; fi
cache: yarn
git:
  depth: 5
